# all social media/online related keys in where did u find this survey collection dict
social_media_list = [
    "tumblr",
    "reddit",
    "discord",
    "patreon",
    "twitter",
    "mastodon",
    "whatsapp",
    "facebook",
    "slack",
    "threads",
    "telegram",
    "t4t",
    "spacehey",
    "pillowfort",
    "substack",
    "cohost",
    "melonland",
    "eunuch",
    "youtube",
    "teams",
    #"zoom",
    "pinterest",
    "lex",
    "twitch",
    "duckduckgo",
    "irc",
    "fetlife",
    "goodreads",
    "insta",
    "quotev",
    "scratch",
    "tiktok",
    "lemmy",
    "signal",
    "wattpad",
    "matrix",
    "neocities",
    "linkedin",
    "ai",
    "bluesky",
    "nonbinary wiki",
    "snapchat",
    "yikyak",
    "google",
    "limonnur",
    "pronouns page",
    "anime feminist",
    "gender census",
    "gender reveal",
    "wikipedia", # we only need this for wikipedia
]
