"""
words that wrongly catch on key words

to sort out at initial collection already
"""

words_catching = {
    "guy": [],
    "dude": [
        "dudette",
    ],
    "boy": [
        "tomboy",
        'noroboyic',
        "hrt femboy", # this is transfemme specific
        'flamboy',
        "boycott",
        "aboyic",
    ],
    "boi": [
        "tomboi",
        "boing",
        "boiling",
        "ameboid"
    ],
    "bot": [
        "robot",
        "both",
        "bottom",
        "botanical",
        "botched",
        "bottle",
        "lobotomy",
        "tombot",
    ],
    "man": [
        "manic",
        "wo/man",
        "woman",
        "mancer",
        "romantic",
        "manidoog",
        "many",
        "(wo)man",
        'neman',
        'talisman',
        'nymangi',
        'maniac', 
        'manipulated', 
        'mannequin',
        "permanen",
        "salamander",
        "doberman",
        "performance",
        "human",
        'femandro', 
        "hooman",
        "manda",
        "romani",
        "charmander",
        "command",
        "dormant",
        "mantis",
        "man-naar-vrouw",
        "(wo)man",
        'seiðmann', 
        "mangle",
    ],
    "male": [
        'nemale', 
        "shemale",
        "male-to-x",
        'malefuta', 
        "female",
        "fe(male)",
    ],
    "sir": [
        'siren',
        'she/sir', 
        "maam+sir",
        "instead of sir",
        "madam sir",
        "maamsir",
    ],
    "lad": [
        "blade",
        "lady",
        "ladies",
        "salad",
        'paladin',
    ],
    "lord": [],
    "dad": [
        "verdad",
    ],
    "mr": [
        "mrs",
        "comrade",
        "mr. potato head",
        'mraow', # fucking cats
        'mreow', 
        'mrow', 
        'mrrp', 
        "mr grinch",
    ],
    "mister": [],
    "son": [
        "song",
        "arson",
        "sone",
        'purrson', 
        'sonnean', 
        "reason",
        "seasoning",
        "sona",
        "person",
    ],
    "bro": [
        "broad",
        "brought",
        "broke", # incl broken
        "abro",
        "brown",
        "fibromyalgia",
    ],
    "bloke": [],
    "bxy": [],
    "bruv": [],

    "girl": [],
    "woman": [],
    "lady": [
        "ladybug"
    ],
    "gal": [
        "galax",
        "galac",
        'regal',
    ],
    "female": [],
    "chic": [],
    "maiden": [],
    # ("ma","am"): [],
    "mom": [
        "moment",
    ],
    "mum": [],
    "miss": [
        'missingno',
        'submissive',
    ],
    "ms": [
        "screams",
        "possums",
        "backrooms",
        "cums", # "cumslut could be genderneutral" - a phrase uttered out loud by me today -.-
        "norms",
        "terms",
        "blossoms",
        "whims",
        "maamsir",
        "msm",
        "thems",
        "worms",
        "himsbian",
        "mamser",
        "mspec",
        "mushrooms",
    ],
    "daughter": [],
    "sister": [],
    "gxrl": [],
    "wxman": [],
    "womxn": [],
    "woman/girl/female": [ # caught by ("ma","am") tuple
        "salamander",
        "swamp man",
        "performance",
        "+man",
        "moss man",
        "a man",
        "paraman",
    ]
}
