"""
words that wrongly catch on key words

to sort out at initial collection already
"""

words_catching = {
    "dude": [
        "dudette",
    ],
    "boy": [
        "tomboy",
        'noroboyic',
        "hrt femboy", # this is transfemme specific
        'flamboy',
        "boycott",
        "aboyic",
    ],
    "boi": [
        "tomboi",
        "boing",
        "boiling",
        "ameboid"
    ],
    "bot": [
        "robot",
        "both",
        "bottom",
        "botanical",
        "botched",
        "bottle",
        "lobotomy",
        "tombot",
    ],
    "man": [
        "manic",
        "wo/man",
        "woman",
        "mancer",
        "romantic",
        "manidoog",
        "many",
        "(wo)man",
        'neman',
        'talisman',
        'nymangi',
        'maniac', 
        'manipulated', 
        'mannequin',
        "permanen",
        "salamander",
        "doberman",
        "performance",
        "human",
        'femandro', 
        "hooman",
        "manda",
        "romani",
        "charmander",
        "command",
        "dormant",
        "mantis",
        "man-naar-vrouw",
        'seiðmann', 
        "mangle",
        "games and draw, man",
        "manner",
    ],
    "male": [
        'nemale', 
        "shemale",
        "male-to-x",
        'malefuta', 
        "female",
        "fe(male)",
    ],
    "sir": [
        'siren',
        'she/sir', 
        "maam+sir",
        "instead of sir",
        "madam sir",
        "maamsir",
    ],
    "lad": [
        "blade",
        "lady",
        "ladies",
        "salad",
        'paladin',
    ],
    "dad": [
        "verdad",
    ],
    "mr": [
        "mrs",
        "comrade",
        "mr. potato head",
        'mraow', # fucking cats
        'mreow', 
        'mrow', 
        'mrrp', 
        "mr grinch",
    ],
    "son": [
        "song",
        "arson",
        "sone",
        'purrson', 
        'sonnean', 
        "reason",
        "seasoning",
        "sona",
        "person",
    ],
    "bro": [
        "broad",
        "brought",
        "broke", # incl broken
        "abro",
        "brown",
        "fibromyalgia",
    ],

    "lady": [
        "ladybug"
    ],
    "gal": [
        "galax",
        "galac",
        'regal',
        "legal",
    ],
    "mom": [
        "moment",
        "your mom",
        "my mom",
    ],
    "mum": [
        "your mum",
        "my mum",
    ],
    "miss": [
        'missingno',
        'submissive',
        "misspelling",
    ],
    "ms": [
        "screams",
        "possums",
        "backrooms",
        "cums", # "cumslut could be genderneutral" - a phrase uttered out loud by me today -.-
        "norms",
        "terms",
        "blossoms",
        "whims",
        "maamsir",
        "msm",
        "thems",
        "worms",
        "himsbian",
        "mamser",
        "mspec",
        "mushrooms",
    ],
    "woman/girl/female": [ # caught by ("ma","am") tuple
        "swamp man",
        "performance",
        "gender+man",
        "moss man",
        "a man",
        "ama", # in various words
        "am not defined as just masculine",
        "man, i just am",
        "i do not use human",
        "mam",
        "amser \(filipino slang i guess\) \(lit\. maa",
        "i am",
        "mammal",
        "manic pixie dream",
    ],

    "both": [
        "bother",
        "both the music and the aesthetic",
    ],

    "trans": [
        "strange",
        "transident",
        "transparent",
        "transcend",
        "transensual",
        "transemph",
        "transformer",
        "transgres",
        "transistor",
        "transhuman",
        "centrangi",
        "trans-neptunian",
        "neutrandrogyne",
        "transkeno",
    ],
    "amab": [
        "thingamabobber",
        "eyeball",
    ],
    "transfemme": [
        "dreamt",
        "mthing",
        "femt",
        "tum",
        "tim",
        "smth",
        "umtsveyik",
    ],
    "transmasc": [
        "drift",
        "aft",
        "shift",
        "oft",
        "reft",
        "fthing",
        "twelfth",
        "left",
        "fifth",
        "transhuman", # caught on trans man I think
    ],

    "fem": [
        "female",
        "feminis",
        "transfem",
        "trans fem",
        "trans-fem",
        "transneufem",
        "cufemian", # idk what this is
        "exparfem", #
        "femache", #
        "cuerpo femenino", # the prompt was "in english"
        "afem", # unsure whether this is negating or no
        "femoid",
    ],
    "ros": [
        "bros",
        "cross",
        "monstrosity",
        "aros",
        "queeros",
        "roseinae", # no idea what this is
        "rosymothic", #
        "roster",
        "corrosive",
        "rosis",
        "prostitute",
        "sexual",
    ],
    "pretty": [
        "pretty sure",
        "pretty cool",
        "pretty much",
    ],
    "masc": [
        "transmasc",
        "trans masc",
        "trans-masc",
        "transneumasc",
        "transnuemasc",
        "amasc",
        "cumascian",
        "masculino", # english only was the prompt
        "mascic",
        "isomasc",
        "masculis",
        "mascharsic", # idk what this means
    ],
    "tom": [
        "tomato",
        "stomach",
        "bottom",
        "pantomime",
        "lobotom",
        "tomb ",
        "auto", 
        "phantom",
    ],

    "andro": [
        "android",
        "gynandro",
        "androgino", # prompt was english only
    ],
    "drag": [
        "dragon",
        "draggy", # idk what that means
    ],
    "cross": [
        "crossroad",
        "crossing",
    ],
    "trav": [
        "travel",
        "trava",
    ],
    "transv": [
        "transvia",
    ],

    "femboy": [
        "feminin",
        "femme",
        "transfem",
    ],
    "trap": [
        "trapped",
    ],

    "auti": [
        "beautiful",
    ],
    "neuro": [
        "neuron",
        "neurotis",
    ],
    "lexi": [
        "flexi",
        "alexi",
    ],
    "alter": [
        "alterhuman",
        "alternat",
        "alterous",
        "altersex",
        "alterbeing",
        "altergender",
        "alterian",
    ],
    "did": [
        "didn't",
        "didhewek",
        "did i use",
    ],

    "nb": [
        "rainbow",
        "chickenbunny",
        "clown",
        "abyss",
        "baby",
        "bycicle",
        " by ",
        "chubby",
        "deeby",
        "\(by ",
        "between",
        "kirby",
        "pubby",
        "scooby",
        "sunboy",
        "bother",
        "xenboy",
        "dragonboy",
        "enban", # idk what these are
        "enbin",
        "enben",
        "unbound",
        "womanboy",
        "nanb", # idk what this means
        "hobby",
        "unboxed",
        "wibby wobby",
    ],
    "cis": [
        "decis",
        "anarc",
        "physic",
        "narcis",
    ],
    "inter": [
        "winter",
        "interest",
        "internet",
        "intergender",
        "interro",
        "internal",
        "interpret",
        "interim",
        "interfac",
        "internon",
        "interpunk",
        "interqueer",
    ],
    "herm": [
        "leatherman",
        "hermit",
    ],
    "lesbian": [
        "less",
        "flesh",
        "molecules",
        "sprinkles",
        "celest",
        "marbles",
        "wobbles",
        "genderless amalgamation of flesh",
        "malespec",
        "multiples",
        "rules",
        "apples",
        "needles",
        "leste",
        "peoples",
        "scales",
        "resembles",
        "holes",
        "achilles",
        "muscles",
        "roles",
        "serbian",
        "sparkles",
        "bianary",
        "coolest",
        "succubian",
    ],
    "bear": [
        "beard",
        "bearing",
    ],
    "homo": [
        "homogen",
        "homonculus",
        "homophile",
    ],
    "other_sexuality_mention": [
        "don't care with gender and sexuality",
        "sexuality is gay",
        "non-binary disaster lesbian",
        "non-binary murder-bird",
        "nonbinary lesbian",
        "non binary lesbian",
        "non-binary, omnisexual",
        "romantic context",
        "sexual context",
        "nonbinary bigender",
        "sexuality free",
        "sexuality is yes and gender is no",
        "sexually homo",
        "not specific to sexuality",
        "gender/sexual sense",
        "hehimsbian/he him lesbian",
        "around in space",
        "adjacent nonbinary",
        "not sexual",
        "my gender and sexuality are linked somehow",
        "non-binary lesbian",
        "nonbinary transsexual female",
        "none biney left beef",
        "sexually ambiguous",
        "expansion of space",
        "tranny of sexual",
        "trans-sexual",
        "transbian/trans lesbian",
        "transbifag",
        "transistorosexual",
        "transsexual menace",
        "transsexual/transexual",
        "abro romantic",
        "bigspace",
        "binary-adjacent",
        "bibinary",
        "niebiniarz",
        "niqabi",
        "nobi",
        "bit nonbinary",
        "binar",
        "amphibi",
        "abigender",
        "ambi",
        "apapangender",
        "bird",
        "bitch",
        "bisexual",
        "bite",
        "expan",
        "participant",
        "visibility",
        "lesb",
        "bian",
        "genderbi",
        "birth",
        "bit",
        "dubious",
        "urbisluxgender",
        "phobi",
        "combination",
        "abimegender",
        "nobia",
        "span",
        "pancake",
        "big",
        "cabin",
        "space",
        "bio",
        "face",
        "menace",
        "barbie",
        "transsexual",
        "transexual",
        "baroque",
        "bibli",
        "bich",
        "bifaux",
        "bimbo",
        "bimodal",
        "birl",
        "bish",
        "bizarre",
        "boobie",
        "adjacent",
        "place",
        "cissexual",
        "debil",
        "pang",
        "ability",
        "around",
        "enbi",
        "homosexual",
        "homesexual",
        "saros",
        "race",
        "vibin",
        "omnisexual",
        "ikke-bin",
        "ickebin",
        "non-bin",
        "nonbin",
        "panagender",
        "panca",
        "panflu",
        "pansy",
        "bill",
        "queersexual",
        "rabi",
        "rebis",
        "robin",
        "romani",
        "panda",
        "unsuaced",
        "pant",
        "zombie",
        "abrosexual",
        "bienby",
        "binaflux",
        "biplane",
        "bisex ",
        "bromance",
        "crustacean",
        "forbid",
        "hijabi",
        "describing",
        "babies",
        "nonbi",
        "pandemigender",
        "panxenogender",
        "peaceful",
        "cupioromantic",
    ],
    "demi/grey" : [
        "grey area",
        "gray area",
        "grey blob",
        "gray blob",
        "earlybluegreytimic",
        "demi-ambonec",
        "demigod",
        "demihuman",
        "demivixen",
        "demivoid",
        "academic",
        "demiambonec",
    ],

    "agender/genderless" : [
        "regardless",
        "countless",
        "meaningless",
        "alia",
        "apa",
        "apora",
        "dialga",
        "drya",
        "enigma",
        "fauna",
        "fluia",
        "gaia",
        "hyena",
        "impla",
        "integra",
        "intra",
        "unless",
        "levia",
        "libra",
        "luna",
        "nebula",
        "para",
        "qua",
        "apatha",
        "bouba",
        "denpa",
        "ilya",
        "cirra",
        "media",
        "meta",
        "musica",
        "nea",
        "nobia", # this may be no bi- a- gender but idc
        "shota",
        "supra",
        "wireless",
    ],
    "neutral" : [
        "neuro",
        "migraine",
        "pneum",
        "neuch",
    ],
    "bigender/genderfull" : [
        "binar",
        "amphibious",
        "abigender",
        "ambi",
        "apapangender",
        "bird",
        "bitch",
        "bisexual",
        "bite",
        "expan",
        "participant",
        "visibility",
        "full of",
        "full yet",
        "lesb",
        "bian",
        "genderbi",
        "birth",
        "helpful",
        "bit",
        "dubious",
        "trin",
        "triple",
        "urbisluxgender",
        "utrinquegender",
        "phobia",
        "combination",
        "abimegender",
        "bi boy",
        "bissexual",
        "eccentric",
        "electri",
        "meaningful",
        "meaninful",
        "playful",
        "flavourful",
        "eldtrich",
        "useful",
        "nobia",
        "purposeful",
        "span",
        "trisgender",
    ],

    "he/him" : [
        # put multi-catchers at the top! so they're looped first
        "the way potheads",
        "headache",
        "this dickhead",
        "them transes you hear",
        "head",
        "hear",
        "hea",
        "the noise sheet",
        "she/they or they/she",
        "he/she/the",
        "she/her/hers",
        "they/them/their",
        "they/them/them",
        "she/her in the",
        "they that's not too she",
        "the-heck",
        "the streets, femme in the sheets",
        "him/her",
        "she/he",
        "she he",
        "he/her",
        "they/them",
        "she/they most of the",
        "she/the",
        "she / the",
        "she the",
        "they/she",
        "they or she",
        "somewhere in the",
        "somewhere on the",
        "somewhere between all of the",
        "somewhere between man and the",
        "somewhere off the",
        "whichever gender is funniest in the",
        "whichever is funnier in the",
        "the way i call my computer a she",
        "the checkout line at the",
        "heshe",
        "he-she",
        "he/she",
        "this bitch right here",
        "tached from the",
        "this once, this the",
        "the color of cherry",
        "other varietals of this",
        "neither here nor there",
        "the owner of this",
        "the ghost piloting this",
        "the hedge",
        "she's the man",
        "she, but like the",
        "eh heh heh",
        "rhetorical",
        "inherent",
        "himiko",
        "hebrew",
        "hermit crab wears a shell",
        "whichever gender that makes this",
        "hermit",
        "the",
        "she",
        "whe",
        "bodhisattva",
        "this",
        "hem",
        "hist",
        "che",
        "ens",
        "chim",
        "didhewek",
        "her",
        "hel",
        "ache",
        "phe",
        "whisp",
        "whim",
        "hebe",
        "heh ",
        "sidhe",
        "hed",
        "fhe",
        "heck",
        "whichever",
        "hispanic",
        "barghest",
        "hetero",
        "hen",
        "shim",
        "heifer",
        "hex",
    ],
    "she/her" : [
        "hermit crab wears a shell",
        "he/she/they",
        "he/she",
        "he-she",
        "he she",
        "she/he ",
        "heshe",
        "ashe",
        "shevik",
        "shell",
        "what she said",
        "where",
        "there",
        "sheet",
        "shelf",
        "cishet", 
        "sheen",
        "she/sir",
        "sheep",
        "hermit",
    ],
    "they/them" : [
        "themed",
    ],
}
